name: Generate Database

on:
  schedule:
    - cron: '0 * * * *'
  push:
    paths:
      - ".github/workflows/generate-source.yml"
      - ".github/scripts/generate/**/*.*"
      - "source/data.json"
      - "source/template.css"
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # v this isn't really needed v
    # strategy:
    #   matrix:
    #     retry-max: [3] # Set the maximum number of retries here

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup PNPM
        working-directory: .github/scripts
        run: |
          npm i -g pnpm
          pnpm i

      - name: Run generate script
        working-directory: .github/scripts
        run: pnpm run generate

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add import.css
          git commit -m "Update import.css (${{ github.sha || 'manual trigger' }})" || true
          git push
