name: Sync branch and replace

env:
    WORKFLOW_TOKEN: ${{ secrets.TOKEN }}
    UPSTREAM_URL: "https://github.com/UserPFP/UserPFP.git"
    UPSTREAM_BRANCH: "main"
    DOWNSTREAM_BRANCH: "main"
    URL: "https://raw.githubusercontent.com/UserPFP/img/main/"
    REPLACE: "https://userpfp.thororen.com/UserPFP-img/"

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitHub Sync to Upstream Repository
        id: sync
        uses: verticalsync/sync-upstream-repo@master
        with:
            upstream_repo: ${{ env.UPSTREAM_URL }}
            upstream_branch: ${{ env.UPSTREAM_BRANCH }}
            downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
            token: ${{ env.WORKFLOW_TOKEN }}
            
      - name: Replace Urls
        run: |
            git config --global user.name 'thororen1234'
            git config --global user.email '78185467+thororen1234@users.noreply.github.com'

            cat source/data.json | while read line
            do
                sed -i "s|${URL}|${REPLACE}|g" "source/data.json"
            done

            git add "source/data.json"

            git commit -m "Replace URL"

            git push main
                