name: Sync branch and replace

env:
    URL: "https://raw.githubusercontent.com/UserPFP/img/main/"
    REPLACE: "https://userpfp.thororen.com/UserPFP-img/"

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitHub Sync to Upstream Repository
        run: |
          git config --global user.name 'thororen1234'
          git config --global user.email '78185467+thororen1234@users.noreply.github.com'
          git remote add upstream "https://github.com/UserPFP/UserPFP.git"
          git fetch upstream
          git checkout main
          git reset --hard upstream/main  
          git fetch --all
          git push origin main --force
            
      - name: Replace Urls
        run: |
            git config --global user.name 'thororen1234'
            git config --global user.email '78185467+thororen1234@users.noreply.github.com'

            cat source/data.json | while read line
            do
                sed -i "s|${URL}|${REPLACE}|g" "source/data.json"
            done

            git add "source/data.json"

            git commit -m "Replace URL"

            git push origin
                